kumuluzee:
  name: users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://172.17.0.1:33333/users
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://172.17.0.1:2379
  discovery:
    etcd:
      hosts: http://172.17.0.1:2379
logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="users">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="42edda9a-bb93-4e5f-87c4-e3607f968174-ls.logit.io" port="23046"
                                                                                         protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'

rest-properties:
  external-services:
    realestate-service:
      enabled: true